### ISSUE TITLE
Mixing up the format of the home page

### ISSUE THREAD

**Issue by angusmason** [circles-png/the-yesterday#16]
so articles are in different layouts, like this:

<img width="1552" alt="IMG_7667" src="https://github.com/circles-png/the-yesterday/assets/100268469/6f1fd760-7376-4364-ab7e-212584775e49">

but the format doesn't change every time you reload it, just every day different articles are in different positions.

- [ ] draw the layout (or is it same as the image)
- [ ] impl

**Comment by circles-png** [comment]
dont have enough articles currently

**Comment by angusmason** [comment]
are there enough now

also on mobile it's fine how it is
it should just be mixed up on desktop
