### ISSUE TITLE
add way of determining the latest articles so that the six latest or something can be placed in order of newest to oldest

### ISSUE THREAD

**Issue by angusmason** [circles-png/the-yesterday#18]

**Comment by angusmason** [comment]
and in all they'd be
newst
|
|
|
˯
oldest

**Comment by angusmason** [comment]
and in each category bit. but latest takes priority over the categories, so no articles repeat.

**Comment by circles-png** [comment]
ab99f2bd8b0539f5f8fe6607dce5f7f1da4aa8ef

first line of file is index, articles are sorted by index ascending
